### ISSUE TITLE
OpTypeImage reports wrong number of operands

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#10]
In [this](https://phabricator.pmoreau.org/F13641) SPIR-V binary (produced from [this](https://phabricator.pmoreau.org/F13640) `.bc`, out of [this](https://phabricator.pmoreau.org/F13639) OpenCL file), `OpTypeImage` ends up being encoded as `1900 0900 0700 0000 0600 0000 0100 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000`. Either the last word is bogus, or it is the AccessQualifier and OpTypeImage is missing it from its operands count.

Also, the same `OpTypeImage` is defined twice, with the exact same parameters (well, except for the result id):
-  `1900 0900 0700 0000 0600 0000 0100 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000`
-  `1900 0900 1500 0000 0600 0000 0100 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000`

**Comment by yxsamliu** [comment]
There are two issues:
1. the word count for OpTypeImage is wrong, which is an easy fix
2. duplicate OpTypeImage. this is due to the image type used in sampled image type is not translated properly.

**Comment by pierremoreau** [comment]
I'll open a new bug report for the duplicated `OpTypeImage`. Thanks for the patch!
