### ISSUE TITLE
Crash during translation of a non-kernel function which calls read_image builtin

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM#116]
llvm-spirv tool crashes during translation of attached kernel.

[test_image.zip](https://github.com/KhronosGroup/SPIRV-LLVM/files/191717/test_image.zip)

Note that tool doesn't crash if  sampFun from the example has __kernel qualifier.

**Comment by bader** [comment]
Pull request #128 should fix that issue.

**Comment by bader** [comment]
Fixed by #128.
