### ISSUE TITLE
Garbage passed as an argument to llvm::Value::setName

### ISSUE THREAD

**Issue by AndreyE** [KhronosGroup/SPIRV-LLVM#16]
LIT test fails on RH6.5 on assertion in llvm::Value::setName (on debug build).

To reproduce:
llvm-lit -v path-to-llvm/test/SPIRV/image-unoptimized.ll
[image-unoptimized.bt.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/49891/image-unoptimized.bt.txt)

**Comment by yxsamliu** [comment]
pull request #25 fixes this.

**Comment by yxsamliu** [comment]
The issue was due to saving StringRef of CallInst->getName() for later use. However StringRef is not safe to cache since the pointee may be freed or overwritten.
