### ISSUE TITLE
Encoding/Decoding does not handle names with spaces properly

### ISSUE THREAD

**Issue by thewilsonator** [KhronosGroup/SPIRV-LLVM#164]
Trips assert `assert(Ch == '\0' && "Invalid string in SPIRV")` in `const SPIRVDecoder& operator>>(const SPIRVDecoder&I, std::string& Str)` in SPIRVStream.cpp

This is because the `std::stream I.IS` does not have `std::noskipws` set

It is perfectly legal to have spaces in the names of llvm type names.

[kernels_ocl120_64-nocrash.spv.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/373734/kernels_ocl120_64-nocrash.spv.txt)
[kernels_ocl120_64-crash.spv.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/373738/kernels_ocl120_64-crash.spv.txt)

**Comment by bader** [comment]
What version do you use?
I think pull request #155 fixed that issue.
The latest version of decoder is able to decode kernels_ocl120_64-crash.spv.txt w/o crashes.

**Comment by thewilsonator** [comment]
d51643a351354f20b9fabae578fdd55117a41c3b 
The merge of PR#135

**Comment by bader** [comment]
Could you try 1eff8420d83c7f6a291792929f6fb92e02f104f0 or later and verify that the issue is fixed, please?

**Comment by thewilsonator** [comment]
1eff842 does not exhibit the crash. Thanks.
