### ISSUE TITLE
llvm.fmuladd.f32 is not code generating properly

### ISSUE THREAD

**Issue by raunintc** [KhronosGroup/SPIRV-LLVM#174]
when a kernel uses the llvm.fmuladd intrinsic we're not generating correct code.

The generated SPIR-V is this:

```
     OpName %8 "llvm.fmuladd.f32"
     OpDecorate %8 LinkageAttributes "llvm.fmuladd.f32" Import
%8 = OpFunction %6 Pure %7
```

   %46 = OpFunctionCall %6 %8 %65 %47 %20

I think llvm-spir needs to emit a opfmul + opfadd.

See attached for an example.

[FancyJuliaSet.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/423789/FancyJuliaSet.txt)

**Comment by AlexeySotkin** [comment]
Fixed by [Translation of LLVM intrinsics #185](https://github.com/KhronosGroup/SPIRV-LLVM/issues/185)
