### ISSUE TITLE
SPIR-V reader translate some conversion/bitcast instructions incorrectly to OCL builtin functions

### ISSUE THREAD

**Issue by yxsamliu** [KhronosGroup/SPIRV-LLVM#20]
pull request #17 caused regression for the following kernel:

__kernel void test_fn( __global char2 *src, __global short *dst )
{
  int tid = get_global_id( 0 );
  short tmp = as_short( src[ tid ] );
  dst[ tid ] = tmp;
}

clang generates the following code:

  %call = tail call spir_func i64 @_Z13get_global_idj(i32 0) #2
  %sext = shl i64 %call, 32
  %idxprom = ashr exact i64 %sext, 32
  %arrayidx = getelementptr inbounds <2 x i8> addrspace(1)\* %src, i64 %idxprom
  %0 = load <2 x i8> addrspace(1)\* %arrayidx, align 2, !tbaa !9
  %astype = bitcast <2 x i8> %0 to i16
  %arrayidx2 = getelementptr inbounds i16 addrspace(1)\* %dst, i64 %idxprom
  store i16 %astype, i16 addrspace(1)\* %arrayidx2, align 2, !tbaa !12
  ret void

SPIRV-V reader translates bitcast <2 x i8> %0 to i16 incorrectly to 

call spir_func i16 @_Z13convert_shortDv2_c(<2 x i8> %1)

Another example:
__kernel void math_kernel8( __global int8\* out, __global float8\* in1, __global float8\* in2 )
{
   int i = get_global_id(0);
   out[i] = isequal( in1[i], in2[i] );
}

The LLVM/SPIR-V translator needs to generate conversion instructions for i1 x 8 -> i32 x 8 for representing isequal() as instruction in SPIR-V. SPIR-V reader should not translate it to OCL builtin function.

**Comment by yxsamliu** [comment]
Let's close this for now since the commit causing regression is reverted. We can reopen this if necessary.

**Comment by AndreyE** [comment]
About isequal. Boolean vectors are not defined by OpenCL C or by SPIR-1.2/2.0 specifications. Also
sext, trunc instructions are defined for scalar types only, so the reader would violate SPIR spec if it generates such instructions for vector types.
So in SPIR-V created from SPIR 1.2/20 operations producing boolean vectors should be always accompanied by casts (sext) to integer vectors. So, it seems like it should be enough to combine these two operations into a single call to OCL built-in returning such integer vector.

**Comment by AndreyE** [comment]
On the second thought since OpenCL doesn't allow boolean vectors then in SPIR-V calls to built-ins like 'isequal' or 'all' should be always accompanied by a cast of boolean vector. So, it seems like it should be enough to combine the operation returning boolean vector and its subsequent cast to integer vector into a single call to OCL built-in returning the integer vector.

**Comment by yxsamliu** [comment]
I think we should relax the restrictions on the LLVM generated from SPIR-V as far as it is compatible with SPIR-V and most backends are able to handle it.

vector of i1 is allowed in SPIR-V and is pretty common in LLVM since it is the result type of vector comparison. I don't think there is a backend unable to handle vector of i1.

**Comment by AndreyE** [comment]
AFAIK LLVM IR doesn't have isnan, isinf and so on. So, they must be translated into calls to built-ins. I expect isequal and isnan are to be handled same way.
IMHO, it is better to be as close to the spec. as possible.
