### ISSUE TITLE
Intrinsic llvm.memmove not supported

### ISSUE THREAD

**Issue by doe300** [KhronosGroup/SPIRV-LLVM#205]
Trying to convert following code to SPIR-V throws an exception.

OpenCL-C code:

    struct SomeStruct
    {
	float16 f;
	int i;
    };

    __kernel void test_struct(const __global struct SomeStruct* in, __global struct SomeStruct* out)
    {
	struct SomeStruct tmp = *in;
	*out = tmp;
    }

OpenCL-C to LLVM-IR compiled with SPIRV-LLVM/SPIR (`clang version 3.6.1 (https://github.com/KhronosGroup/SPIR d7e44c3b27581e54ca0e522987d1ade2bd29b70d) (https://github.com/KhronosGroup/SPIRV-LLVM.git fffc52b7fb3552c045c398d68e22216c8d770c00)`)
LLVM-IR code (excerpt):

    %struct.SomeStruct = type { <16 x float>, i32, [60 x i8] }
    define spir_kernel void @test_struct(%struct.SomeStruct addrspace(1)* nocapture readonly %in, %struct.SomeStruct addrspace(1)* nocapture %out) #0 {
      %1 = bitcast %struct.SomeStruct addrspace(1)* %in to i8 addrspace(1)*
      %2 = bitcast %struct.SomeStruct addrspace(1)* %out to i8 addrspace(1)*
      call void @llvm.memmove.p1i8.p1i8.i32(i8 addrspace(1)* %2, i8 addrspace(1)* %1, i32 128, i32 64, i1 false)
      ret void
    }

    declare void @llvm.memmove.p1i8.p1i8.i32(i8 addrspace(1)* nocapture, i8 addrspace(1)* nocapture readonly, i32, i32, i1)

As you can see, this should be a simple mem-copy, but `llvm-spirv`throws:

    InvalidFunctionCall: Unexpected llvm intrinsic:  [Src: /opt/SPIRV-LLVM/lib/SPIRV/SPIRVWriter.cpp:1314  ]
    Fails to save LLVM as SPIRV: InvalidFunctionCall: Unexpected llvm intrinsic:  [Src: /opt/SPIRV-LLVM/lib/SPIRV/SPIRVWriter.cpp:1314  ]

**Comment by yxsamliu** [comment]
It seems the translator is unable to translate llvm.memmove.

One solution might be create a temp var, copy to it, then copy to target, i.e. the same way done in the source.

**Comment by doe300** [comment]
This is the converted LLVM IR from the source code given above, the temporary variable is optimized away by `-O3`, which makes kind of sense, since it is never used.

**Comment by yxsamliu** [comment]
I mean for the translator to translate llvm.memmove to SPIRV, the translator can create a temp var, copy to it then copy to target in LLVM IR, then translate the LLVM IR to SPIRV.
