### ISSUE TITLE
Duplicate `OpTypeImage` definition

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#22]
In [this](https://phabricator.pmoreau.org/F13641) SPIR-V binary (produced from [this](https://phabricator.pmoreau.org/F13640) `.bc`, out of [this](https://phabricator.pmoreau.org/F13639) OpenCL file), `OpTypeImage` is defined twice, with the exact same parameters (well, except for the result id):
-  `1900 0900 0700 0000 0600 0000 0100 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000`
-  `1900 0900 1500 0000 0600 0000 0100 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000`

**Comment by bader** [comment]
Hi Pierre,

Please, verify that this issue is fixed by Sam in rev. b03f4776295403f7622c56897eeea746117cd144.

Thanks,
Alexey

**Comment by pierremoreau** [comment]
Hi Alexey,

Just tested the latest version of `khronos/spirv-3.6.1` and the issue is fixed! Thanks for the fix @yxsamliu!

Thanks,
Pierre
