### ISSUE TITLE
Missing `SPIRVSubTarget.h` file

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#23]
While trying to compile the new `spirv-target` branch, I get the following error:

```
In file included from ../lib/Target/SPIRV/SPIRVISelDAGToDAG.cpp:44:
../lib/Target/SPIRV/SPIRVTargetMachine.h:41:10: fatal error: 'SPIRVSubTarget.h' file not found
#include "SPIRVSubTarget.h"
```

@yxsamliu Did you forget to push this file? :-)

**Comment by yxsamliu** [comment]
Did you use CMake to build? It works for me on both MSVC 2013 and cygwin.
The Makefile in the directory itself may not work.

**Comment by pierremoreau** [comment]
Gotcha! The file is named `SPIRVSubtarget.h` and not `SPIRVSubTarget.h`, which will of course work on Windows since it's case insensitive, but not on Linux. As only `SPIRVTargetMachine.h` is calling it `SPIRVSubTarget.h`, I guess the name was meant to be `SPIRVSubtarget.h`. I'll write a patch.

**Comment by yxsamliu** [comment]
My bad :-) Thanks for fixing this.

**Comment by pierremoreau** [comment]
No problem! I would say this is one of the most common kind of errors when trying to build a Windows project on Linux/Mac OS. :-D
