### ISSUE TITLE
llvm-spirv tool crashes during conversion of enqueue_kernel function call

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM#28]
Current implementation assumes that last argument of the `enqueue_kernel` call is bitcast from llvm block type to void()*.
This assumption is not always true;

To reproduce run `llvm-as < extExecution.ll.txt | llvm-spir`

[extExecution.ll.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/59573/extExecution.ll.txt)
[extExecution.cl.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/59572/extExecution.cl.txt)

**Comment by yxsamliu** [comment]
This test is invalid. According to OCL 2.0 spec rev 31:

Block variable declarations must be qualified with const. Therefore all block variables must be initialized at declaration time and may not be reassigned.
