### ISSUE TITLE
Generated Linkage Attribute OpDecorate doesn't contain a literal string

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#3]
Translating [this LLVM code](https://phabricator.pmoreau.org/F12263) using `llvm-spirv` results in [this SPIR-V binary](https://phabricator.pmoreau.org/F12264), where the `OpDecorate LinkageAttributes` only has the linkage type but no name. (The corresponding binary stream is `4700 0400 0500 0000 2900 0000 0000 0000`.)

The code assumes the linkage type is the first attribute, which seems wrong when looking at the specification. Furthermore, there is no way to set both attributes as only the `SPIRVDecorate*` constructor modifies the `Literals` vector storing the attributes, and it only takes one word.

Note: If needed, the initial OpenCL kernel can be found [here](https://gist.github.com/pierremoreau/586f3e5ed1b9688dbf88).

**Comment by yxsamliu** [comment]
"the OpDecorate LinkageAttributes only has the linkage type but no name"

By 'name' do you mean the function name?

**Comment by pierremoreau** [comment]
Could be the function name maybe, I am not really sure what it is supposed to be. From the specification:

> Within a module, imported or exported values are decorated using the Linkage Attributes Decoration. This decoration assigns the following linkage attributes to decorated values:
> -    A Linkage Type.
> -    A name, which is a Literal String, and is used to uniquely identify exported values.

**Comment by yxsamliu** [comment]
I see.

It is the name of the function or global variable. We should have a null terminated string (0 padded at the end if the string length plus 1 is not multiple of 4), then followed by the linkage type.

**Comment by pierremoreau** [comment]
Right, that's my understanding as well. I could try to write the patch for it, but I'm unsure on how to proceed: changing the constructor to take a vector of word rather than just one word, add a setter or an `addLiteral()`/`appendWord()`, or another approach? Or if you have an idea on how to proceed, feel free to do it. :-)

**Comment by yxsamliu** [comment]
I am thinking to derive SPIRVDecorateLinkageAttr from SPIRVDecorate. Add a constructor to accept name and linkage type, and pipe them into the SPIRVDecorateGeneric::Literals. Also add a convenience member function to get the name as std::string and linkage type. This way it is still a normal SPIRVDecorate and has minimal impact on other codes.

Have utility functions to convert a string to a vector of word and back may be useful for future use and make the code clearer.

I am working on some other bugs. Your help is really appreciate it. Otherwise I will fix it. :-)

**Comment by pierremoreau** [comment]
Seems like a good idea! :-) I'll try to hack a pull request, and it will be easy to update it if needed.

After some more thinking, it would be good to modify the constructor to take a vector of word, to be able to accept the literal numbers from decorations `ArrayStride`, `MatrixStride`, and so on. And this should be enough, as OpName are supposed to be placed before OpDecorate instructions.

Should the utility functions for converting back and forth between a string and a vector of word be placed in `lib/SPIRV/libSPIRV/SPIRVEnum.h` or somewhere else?

**Comment by yxsamliu** [comment]
you can add it to lib/SPIRV/libSPIRV/SPIRVUtil.h.

**Comment by yxsamliu** [comment]
oops I may have merged the [WIP] request prematurely. Is it supposed to be merged later?

**Comment by pierremoreau** [comment]
I had a couple of comments in the pull request description talking about a v2, and what could be improved. But they could be done as a separate patch as well.

Maybe I should have attached the patch to the issue first to get some feedback on it rather than open a pull request for it? But at least I know you can put comments on the patch in a pull request, and update the pull request, whereas I have no idea if you can do the same in an issue.

**Comment by yxsamliu** [comment]
Thanks for your explanation. Actually I noticed your comments about v2 but I missed the [WIP] in the merge request. I think we will keep this merge since the change is functional as a fix. Next time I will wait until there is no [WIP] in the pull request then merge. :-)

**Comment by yxsamliu** [comment]
There are two issues found: 1. build failure with MSVC due to missing declaration for uint32_t. 2. For name length being multiple of 4, the terminating null is not appended to the word. I have fixed these two issues in the recent commit.

**Comment by pierremoreau** [comment]
Argh, you're right… Thank you for fixing those! I'll get back to the other issues tomorrow.
