### ISSUE TITLE
`DataLayout::getSmallestLegalIntType` returns nullptr since `LegalIntWidths` is empty

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#42]
Even with 0dfb100, `LegalIntWidths` remains empty since none of the `Desc` fed to `DataLayout` contains an 'n' attribute (which is the only case where `LegalIntWidths` will be appended new elements).

**Comment by pierremoreau** [comment]
The `Desc` fed to `DataLayout` is hardcoded (see [here](https://github.com/KhronosGroup/SPIRV-LLVM/blob/spirv-backend/lib/Target/SPIRV/SPIRVSubtarget.cpp#L64)) and wasn't changed by 0dfb100. I tried modifying that directly to add a '-n32:32:32' but got

```
error: backend data layout 'e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-n32:32:32'
does not match expected target description 'e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024'
```

I'll keep hacking at it.

**Comment by pierremoreau** [comment]
Ah! I also needed to edit [`tools/clang/lib/Basic/Targets.cpp:6369`](https://github.com/KhronosGroup/SPIR/blob/spirv-1.0/lib/Basic/Targets.cpp#L6369) to add the `-n32` there as well. And with those changes in, `getSmallestLegalIntType()` doesn't return a nullptr. I had a quick look at the remaining of the `Targets.cpp` file, and it looks like every target defined there has a `-n` in its `DescriptionString`.

I guess we should add at least `-n32:64`, but since `OpTypeInt` takes an arbitrary width in bits, it could go down to 1 or 0, and up to infinity, so I am unsure if it should rather be `-n8:16:32:64` or something else.

**Comment by pierremoreau** [comment]
So far, I have pierremoreau@8fc0e1b9e6cb8f3d62c5eba35fb2e94274017ae1 and pierremoreau/SPIR@d97b2deb2f86f2bdef8a27ed6f6ee1f6db6f6058, but I feel like more sizes should be advertised. Do you have any opinion on which ones?

**Comment by bader** [comment]
I think all "natively supported" OpenCL integer types must be native for SPIR-V target (i.e. -n8:16:32:64), although 8, 16 and 64-bit integers require additional capabilities in SPIR-V.

**Comment by pierremoreau** [comment]
I'm not sure if it is possible to dynamically generate that layout list, but that would be better, since we don't want to force 8-bit support if the kernel doesn't even use it. I'll look into that.

**Comment by pierremoreau** [comment]
I switched back to the `spirv-3.6.1` branch, and I’m encountering the same issue. Since there is no SPIR-V target, it’s the `SPIR32TargetInfo.DescriptionString` and the `SPIR64TargetInfo.DescriptionString` which need to be patched. It doesn’t look like 8, 16 or 64-bit integers require additional capabilities, but I only looked at the specification really quickly.
