### ISSUE TITLE
SPIR-V generator doesn't generate OpGetDefaultQueue

### ISSUE THREAD

**Issue by AndreyE** [KhronosGroup/SPIRV-LLVM#45]
Reproducer:
set PATH_TO_GEN to spirv-1.0 generator install directory
And run (in bash)
${PATH_TO_GEN}/bin/clang -cc1 -x cl -cl-std=CL2.0 -triple spir64-unknonw-unknown -emit-spirv -include ${PATH_TO_GEN}/lib/clang/3.6.1/include/opencl-20.h [repro.cl](https://github.com/KhronosGroup/SPIRV-LLVM/files/108067/repro.txt) -o /tmp/out.spv && ./llvm-spirv -to-text /tmp/out.spv  -o - | grep -i default

Expected:
GetDefaultQueue operation
Actual:
7 Name 4 "get_default_queue"
9 Decorate 4 LinkageAttributes "get_default_queue" Import

**Comment by bader** [comment]
It was the issue in the way this built-in is defined in the header file. It was not marked as overloadable, so LLVM/SPIR-V translator didn't recognize it as OpenCL built-in function. I added this attribute at https://github.com/KhronosGroup/SPIR/commit/beccb14fcb6f00bf5d4051ae398a6e9fbef17b71, although it doesn't make too much sense to make this built-in function overloadable - it has no parameters.
