### ISSUE TITLE
Capabilities required by OpDecorate are not added to SPIR-V

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#5]
When generating a [SPIR-V binary](https://phabricator.pmoreau.org/F12264) from the sames files as in #3 ([LLVM code](https://phabricator.pmoreau.org/F12263) and [OpenCL kernel](https://gist.github.com/pierremoreau/586f3e5ed1b9688dbf88)), no `OpCapability Kernel` is generated (required by `OpEntryPoint Kernel`, `OpMemoryModel OpenCL`, `OpDecorate FuncParamAttr`, `OpDecorate Constant`), nor `OpCapability Linkage`, which is required by `OpDecorate LinkageAttributes`

**Comment by pierremoreau** [comment]
Hum… I do realise that missing capabilities is not restricted to `OpDecorate` instructions, but is something more widespread.

**Comment by yxsamliu** [comment]
Agree we should add OpCapability Kernel for those situations.

**Comment by yxsamliu** [comment]
Can you create a pull request for your fix about Capability dependencies? Thanks.

**Comment by pierremoreau** [comment]
I created #18.
