### ISSUE TITLE
Wrong encoding of complex constant initialization

### ISSUE THREAD

**Issue by rfsaliev** [KhronosGroup/SPIRV-LLVM#50]
In case of complex constant initialization of automatic variables, SPIRV contains global variable declaration with Storage Class: Function.
[ArrInit.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/117266/ArrInit.txt)

CL code example:
`kernel void test() { uint arr[] = { 123, 456 }; }`

Expected:

```
         ...
          %9 = OpVariable %8 UniformConstant %7
         %12 = OpFunction %10 None %11
         ...
               OpFunctionEnd
```

Actual:

```
         ...
          %9 = OpVariable %8 Function %7
         %12 = OpFunction %10 None %11
         ...
               OpFunctionEnd
```

**Comment by yxsamliu** [comment]
In SPIR-V, alloca is represented as OpVariable with Function storage. see https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.pdf section 2.4 page 19.

**Comment by pierremoreau** [comment]
Except here the `OpVariable Function` instruction looks outside of any actual function body, which is contrary to the spec.

**Comment by yxsamliu** [comment]
Actually that is for a global var in the LLVM IR:

@test.arr = private unnamed_addr constant [2 x i32] [i32 123, i32 456], align 4

**Comment by yxsamliu** [comment]
You are right, here we do need UniformConstant storage.

**Comment by pierremoreau** [comment]
Looking at the generated SPIR-V found in `ArrInit.txt`, this is not the only error.
- `%17 = OpVariable %8 Function` is found right after a `%16 = OpBitcast %15 %9`, which is contrary to the spec:
  
  >  OpVariable instructions in a function must be in the first block in the function. These instructions, together with any immediately preceding OpLine instructions, must be the first instructions in that block. (Note the validation rules prevent OpPhi instructions in the first block of a function.)
- `%18 = OpBitcast %15 %17` seems rather suspect: why bitcast a variable which has never been initialised?

**Comment by AlexeySotkin** [comment]
We can see the same problem with the following(slightly different) code:
`kernel void  test() { const int arr[] = { 123, 456 }; }`
For this example Clang generate global constant and empty function body:
```
@test.arr = internal constant [2 x i32] [i32 123, i32 456], align 4

; Function Attrs: nounwind
define spir_kernel void @test() #0 {
entry:
  ret void
}
```
Then after translation of the IR above to SPIR-V only global variable with wrong(Function) storage class remains.

But if I compile it with `-fno-merge-all-constants` flag I got the following IR:
```
@test.arr = private addrspace(2) constant [2 x i32] [i32 123, i32 456], align 4

; Function Attrs: nounwind
define spir_kernel void @test() #0 {
entry:
  %arr = alloca [2 x i32], align 4
  %0 = bitcast [2 x i32]* %arr to i8*
  call void @llvm.memcpy.p0i8.p2i8.i32(i8* %0, i8 addrspace(2)* bitcast ([2 x i32] addrspace(2)* @test.arr to i8 addrspace(2)*), i32 8, i32 4, i1 false)
  ret void
}
```
This IR, looks slightly more complicated, but it can be translated to well-formed SPIR-V.

The questions is: Shall we have this flag always enabled in the SPIR generator?

**Comment by yxsamliu** [comment]
The kernel has no observable effects. To me it can just be translated to an empty kernel. The latter representation is not better than the previous representation.

**Comment by AlexeySotkin** [comment]
The following code has observable effect
```
__kernel void test(__global int *x) {
	const int arr[] = {123, 456};
	*x = arr[1];
}
```
In this case the SPIR generator produces the following IR:
```
@test.arr = internal constant [2 x i32] [i32 123, i32 456], align 4

; Function Attrs: nounwind
define spir_kernel void @test(i32 addrspace(1)* %x) #0 {
entry:
  %0 = load i32* getelementptr inbounds ([2 x i32]* @test.arr, i32 0, i32 1), align 4
  store i32 %0, i32 addrspace(1)* %x, align 4
  ret void
}

```

The problem is still here: there is a global variable `@test.arr` with private address space, which contradicts with SPIR-V specification in a way described in the beginning of this issue.
With `fno-merge-all-constants` we do keep alloca for the array in private AS.
```
@test.arr = private addrspace(2) constant [2 x i32] [i32 123, i32 456], align 4

; Function Attrs: nounwind
define spir_kernel void @test(i32 addrspace(1)* %x) #0 {
entry:
  %arr = alloca [2 x i32], align 4
  %0 = bitcast [2 x i32]* %arr to i8*
  call void @llvm.memcpy.p0i8.p2i8.i32(i8* %0, i8 addrspace(2)* bitcast ([2 x i32] addrspace(2)* @test.arr to i8 addrspace(2)*), i32 8, i32 4, i1 false)
  %arrayidx = getelementptr inbounds [2 x i32]* %arr, i32 0, i32 1
  %1 = load i32* %arrayidx, align 4
  store i32 %1, i32 addrspace(1)* %x, align 4
  ret void
}

```
This aligns with both: declaration of the array in private AS in the source file, and can be correctly represented in SPIR-V.

**Comment by yxsamliu** [comment]
Right. Probably we should force -fno-merge-all-constants when emitting for SPIR-V.

I am just wondering whether we should let the translator do a similar translation when it sees a constant global variable in private address space. It seems doable.

**Comment by AlexeySotkin** [comment]
Yes, another solution might be to write/modify a pass which will insert alloca, bitcast and memcpy as needed.
I already have the fix with -fno-merge-all-constants. For now, it looks sufficient to me. Could you review?

**Comment by AlexeySotkin** [comment]
Having a const-qualified variable in the private address space probably is not what the user wants. I think it makes more sense to allocate the variable in the constant address space. Maybe a "fix-it hint" should be issued in this case.
