### ISSUE TITLE
get_local_id(X) marked as LinkageAttributes export

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#6]
When generating a [SPIR-V binary](https://phabricator.pmoreau.org/F12264) from the sames files as in #3 ([LLVM code](https://phabricator.pmoreau.org/F12263) and [OpenCL kernel](https://gist.github.com/pierremoreau/586f3e5ed1b9688dbf88)), `get_local_id(X)` is marked as an exported function, which seems wrong as the kernel doesn't define but rather import it.

**Comment by pierremoreau** [comment]
The specification defines import as:

> A declaration of a global variable or a function that exists in another module.

which could fit in this case, though I'm unsure if we can defne `get_local_id(X)` as being defined in another module, and export is defined as:

> Accessible by other modules as well.

which, I find, is quite vague.

**Comment by yxsamliu** [comment]
Agree that the global variables for LocalInvocationId etc should have import linkage, since multiple modules are supposed to share the same set of global variables defined somewhere else.

**Comment by yxsamliu** [comment]
This seems to be a special case of a more generic issue. All declarations should have Import Linkage in SPIR-V. There will be a fix for this and other linkage issues.

**Comment by pierremoreau** [comment]
Great! I tried to have a look at it, thinking I would change the code to have at least built-in variables marked as Import, but I got stuck on trying to figure out where the `GlobalValue::AvailableExternallyLinkage` was coming from.

**Comment by bader** [comment]
#29 is merged, so this issue should be resolved

**Comment by pierremoreau** [comment]
Right, I had forgotten to fo it.
