### ISSUE TITLE
The names of built-in variables don't match the documentation

### ISSUE THREAD

**Issue by bsochack** [KhronosGroup/SPIRV-LLVM#89]
The documentation (https://github.com/KhronosGroup/SPIRV-LLVM/blob/khronos/spirv-3.6.1/docs/SPIRVRepresentationInLLVM.rst#id9) says that the built-in variables should have names:
__spirv_BuiltIn{Name}

In the SPIR-V converter (https://github.com/KhronosGroup/SPIRV-LLVM/blob/khronos/spirv-3.6.1/lib/SPIRV/libSPIRV/SPIRVEnum.h#L229) these built-ins don't have "BuiltIn" prefix.
Is this generator bug or documentation?

Personally I'd prefer the names with "BuiltIn" prefix.

**Comment by yxsamliu** [comment]
I think the documentation is right. The translator is done before the documentation therefore is outdated. We should fix the translator.

**Comment by bsochack** [comment]
I can take care of fix. I'll open a pull request tomorrow

**Comment by bsochack** [comment]
https://github.com/KhronosGroup/SPIRV-LLVM/pull/97

**Comment by bader** [comment]
Fixed by #97.
