### ISSUE TITLE
Shader and Matrix capabilities are added to the kernels when StorageClassFunction is used

### ISSUE THREAD

**Issue by bsochack** [KhronosGroup/SPIRV-LLVM#90]
There is a small bug in the SPIRVEnum.h file (https://github.com/KhronosGroup/SPIRV-LLVM/blob/khronos/spirv-3.6.1/lib/SPIRV/libSPIRV/SPIRVEnum.h#L442) which causes that "Shader" and "Matrix" capabilities are added to the OpenCL kernels when StorageClassFunction is used.
The storage class function is common for shaders and kernels.

BTW, StorageClassPushConstant is missing in the mapping.

**Comment by pierremoreau** [comment]
This was a bug in the original SPIR-V specification, but it remained in `SPIRVEnum.h` since the header was not updated. This should be fixed by #8. Except I'm not updating the maps… I will add that as well. That should also fix `StorageClassPushConstant` missing from the mapping.

**Comment by bsochack** [comment]
Thank you
