### ISSUE TITLE
read_imagef with image2d_t and sampler_t causes regression

### ISSUE THREAD

**Issue by aaronenyeshi** [KhronosGroup/SPIRV-LLVM#93]
Due to recent changes, a new regression was created. 

Please see the attached .cl file
[test.zip](https://github.com/KhronosGroup/SPIRV-LLVM/files/166239/test.zip)

Compiled using clang (into .bc file) in command line:
clang -cc1 -internal-isystem C:\llvmspirv\build\Debug\lib\clang\3.6.1\include -nostdsysteminc -x cl -cl-std=CL1.2 -include C:\llvmspirv\build\Debug\lib\clang\3.6.1\include\opencl-12.h -emit-llvm-bc -triple spir64-unknown-unknown -O0

Ran using llvm-spirv in command line:
llvm-spirv -spirv-debug -spirv-text test.bc

**Comment by aaronenyeshi** [comment]
[output.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/166257/output.txt)

Here is the output from llvm-spirv.

**Comment by bader** [comment]
aaronenyeshi, since it's a regression could you specify the revision that works for you?

**Comment by aaronenyeshi** [comment]
Last one that worked for me was : 38443820c5c91d4c0bcca9eaa452b87db3f4c443

**Comment by bader** [comment]
Should be fixed by https://github.com/KhronosGroup/SPIRV-LLVM/commit/1e6a217c6835e959985aa688c1e07f28696e7df0.
Please, verify.

**Comment by aaronenyeshi** [comment]
Hi Alexey Bader. I have confirmed that this issue is fixed as of 1e6a217. Thanks!
