### ISSUE TITLE
atomic_inc from round trip spirv translated llvm causes regression

### ISSUE THREAD

**Issue by aaronenyeshi** [KhronosGroup/SPIRV-LLVM#98]
Seems a new regression has appeared with the translation of atomic_inc.

I have included the testcase to reproduce the issue. Also I have attached the translated llvm before regression and after regression. The translated llvm is now incorrect.

[test.zip](https://github.com/KhronosGroup/SPIRV-LLVM/files/172595/test.zip)

The main differences: 
@_Z10atomic_incPVU3AS1i(i32 addrspace(1)\* %count)
has become 
 @_Z10atomic_incPVU3AS1iii(i32 addrspace(1)\* %count, i32 1, i32 16)

So declaration changed from:
declare spir_func i32 @_Z10atomic_incPVU3AS1i(i32 addrspace(1)_) #0
into
declare spir_func i32 @_Z10atomic_incPVU3AS1iii(i32 addrspace(1)_, i32, i32) #0

**Comment by aaronenyeshi** [comment]
Last revision that worked for me was: 38443820c5c91d4c0bcca9eaa452b87db3f4c443

**Comment by AlexeySotkin** [comment]
PR #94 should fix the problem.

**Comment by aaronenyeshi** [comment]
Great, thanks for the fix!
